### ISSUE TITLE
stream-extractor mistakes UDP packets for TCP

### ISSUE THREAD

**Issue by Pommaq** [genonullfree/stream-extractor#13]
This essentially breaks this tool's protocol filtering causing "Extract" command to produce Pcap files containing Udp streams along with the intended Tcp stream files. The source of the bug is from StreamInfo::new() where

```rust
impl StreamInfo {
    pub fn new(input: &EthernetPacket) -> Option<Self> {
        let ipv4 = Ipv4Packet::new(input.payload())?;
            if let Some(tcp) = TcpPacket::new(ipv4.payload()) {
                return Some(Self {
                    /*Snip*/
                    packet_type: PacketType::Tcp,
                });
            } else if let Some(udp) = UdpPacket::new(ipv4.payload()) {
                return Some(Self {
                    /*Snip*/
                    packet_type: PacketType::Udp,
                });
            }
            /*Snip*/
    }

/*snip*/
}
```

Do you see it?
We naively parse the IPv4 packet contents as TCP and only do UDP parsing if it didn't work. The issue here is that TCP packet headers are at minimum 20 bytes, and UDP headers are 8, yet most UDP packets do actually contain data in their body, which is usually enough to match the size of TCP headers or more.

This causes TcpPacket::new() to successfully create a tcp packet from UDP data, resulting in the bug.

The solution comes from the OSI Network layer (this case, IPv4 header). It contains a protocol-type field that explicitly tells us what protocol is in the transport layer (This tool appears to be focused on UDP and TCP only). The solution is thus something like

```rust
use pnet::packet::ip::IpNextHeaderProtocols;

impl StreamInfo {
    pub fn new(input: &EthernetPacket) -> Option<Self> {
        let ipv4 = Ipv4Packet::new(input.payload())?;
        let next_proto= ipv4.get_next_level_protocol();
        
        if next_proto == IpNextHeaderProtocols::Tcp {
            // It's TCP.
            let tcp =  TcpPacket::new(ipv4.payload())?;
            return Some(Self {
                /*snip*/
                packet_type: PacketType::Tcp,
            });
        }
        // Else, it's something unknown or Udp. Considering the usecase of this tool we can probably just 
        // drop it to avoid unecessary memory usage?
        
        if next_proto == IpNextHeaderProtocols::Udp {
            // It'd UDP
            return Some(Self {
                /*snip*/
                packet_type: PacketType::Udp,
            });
        }
        /*snip*/
    }
}
```

**Comment by Pommaq** [comment]
Do note that this solution has a similar problem now. Pcap files that contain traffic other than ipv4 probably break just as fashionably, I havent tested but e.g. Ipv6 could die in similar ways

**Comment by genonullfree** [comment]
Awesome, thank you for the detailed issue! I have pushed a fix for it that seems to work correctly on my test pcaps. Please let me know if you see any other issues with this fix.
